// Code generated by aru model:build from model.go. DO NOT EDIT.

package activitylog

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Activities starts a query on the table of Activity, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Activities(db model.DB) *ActivityQuery { return &ActivityQuery{b: activityTable.Query(db)} }

// ActivityQuery is a query on the table of Activity.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Activity rows or a value; there is
// no way to run one without a Grant.
type ActivityQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *ActivityQuery) Base() *model.Builder { return q.b }

// New returns an empty Activity on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *ActivityQuery) New() (*Activity, error) {
	e, err := q.b.NewModelInstance(nil)
	return activityOf(e), err
}

// ActivityCollection is rows of Activity, as a query returns them.
type ActivityCollection []*Activity

// ActivityCollectionOf converts rows of the table of Activity. A nil input is a nil
// collection.
func ActivityCollectionOf(rows model.Rows) ActivityCollection {
	if rows == nil {
		return nil
	}
	out := make(ActivityCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Activity)
	}
	return out
}

func activityOf(e model.Entity) *Activity {
	row, _ := e.(*Activity)
	return row
}

// activityColumn turns a closure over ActivityQuery into one over the core builder, so
// passing func(*ActivityQuery) where a column goes adds a parenthesised group.
func activityColumn(column any) any {
	if group, ok := column.(func(*ActivityQuery)); ok {
		return func(b *model.Builder) { group(&ActivityQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *ActivityQuery) Clone() *ActivityQuery { return &ActivityQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*ActivityQuery) in place of the column adds a group.
func (q *ActivityQuery) Where(column any, args ...any) *ActivityQuery {
	q.b.Where(activityColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*ActivityQuery) in place of the column adds a group.
func (q *ActivityQuery) OrWhere(column any, args ...any) *ActivityQuery {
	q.b.OrWhere(activityColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *ActivityQuery) WhereNot(column any, args ...any) *ActivityQuery {
	q.b.WhereNot(activityColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *ActivityQuery) OrWhereNot(column any, args ...any) *ActivityQuery {
	q.b.OrWhereNot(activityColumn(column), args...)
	return q
}

func (q *ActivityQuery) WhereIn(column any, values []any) *ActivityQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *ActivityQuery) WhereNotIn(column any, values []any) *ActivityQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *ActivityQuery) WhereNull(columns ...any) *ActivityQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *ActivityQuery) WhereNotNull(columns ...any) *ActivityQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *ActivityQuery) WhereBetween(column any, from, to any) *ActivityQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *ActivityQuery) WhereColumn(first any, args ...any) *ActivityQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *ActivityQuery) WhereKey(id any) *ActivityQuery {
	q.b.WhereKey(id)
	return q
}

func (q *ActivityQuery) WhereExists(callback func(*query.Builder)) *ActivityQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *ActivityQuery) WhereNotExists(callback func(*query.Builder)) *ActivityQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *ActivityQuery) WhereHas(relation string, callback func(*query.Builder)) *ActivityQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *ActivityQuery) OrWhereHas(relation string, callback func(*query.Builder)) *ActivityQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *ActivityQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *ActivityQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *ActivityQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *ActivityQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *ActivityQuery) WhereRelation(relation string, column any, args ...any) *ActivityQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *ActivityQuery) OrWhereRelation(relation string, column any, args ...any) *ActivityQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *ActivityQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *ActivityQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *ActivityQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *ActivityQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *ActivityQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *ActivityQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *ActivityQuery) OrHas(relation, operator string, count int) *ActivityQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *ActivityQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *ActivityQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *ActivityQuery) OrDoesntHave(relation string) *ActivityQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *ActivityQuery) Select(columns ...any) *ActivityQuery {
	q.b.Select(columns...)
	return q
}

func (q *ActivityQuery) AddSelect(columns ...any) *ActivityQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *ActivityQuery) SelectRaw(expression string, bindings ...any) *ActivityQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *ActivityQuery) Join(table any, first any, args ...any) *ActivityQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *ActivityQuery) GroupBy(groups ...any) *ActivityQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *ActivityQuery) OrderBy(column any, direction ...string) *ActivityQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *ActivityQuery) OrderByDesc(column any) *ActivityQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *ActivityQuery) Latest(column ...string) *ActivityQuery {
	q.b.Latest(column...)
	return q
}

func (q *ActivityQuery) Oldest(column ...string) *ActivityQuery {
	q.b.Oldest(column...)
	return q
}

func (q *ActivityQuery) Limit(value int) *ActivityQuery {
	q.b.Limit(value)
	return q
}

func (q *ActivityQuery) Offset(value int) *ActivityQuery {
	q.b.Offset(value)
	return q
}

func (q *ActivityQuery) ForPage(page, perPage int) *ActivityQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *ActivityQuery) With(relations ...string) *ActivityQuery {
	q.b.With(relations...)
	return q
}

func (q *ActivityQuery) WithCount(relations ...string) *ActivityQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *ActivityQuery) WithExists(relation string) *ActivityQuery {
	q.b.WithExists(relation)
	return q
}

func (q *ActivityQuery) WithSum(relation, column string) *ActivityQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *ActivityQuery) WithAvg(relation, column string) *ActivityQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *ActivityQuery) WithMin(relation, column string) *ActivityQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *ActivityQuery) WithMax(relation, column string) *ActivityQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *ActivityQuery) Without(relations ...string) *ActivityQuery {
	q.b.Without(relations...)
	return q
}

func (q *ActivityQuery) WithoutGlobalScope(identifier string) *ActivityQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *ActivityQuery) WithoutGlobalScopes(identifiers ...string) *ActivityQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *ActivityQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (ActivityCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return ActivityCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *ActivityQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Activity, error) {
	e, err := q.b.First(ctx, g, columns...)
	return activityOf(e), err
}

func (q *ActivityQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Activity, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return activityOf(e), err
}

func (q *ActivityQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Activity, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return activityOf(e), err
}

func (q *ActivityQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Activity, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return activityOf(e), err
}

func (q *ActivityQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Activity, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return activityOf(e), err
}

func (q *ActivityQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Activity, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return activityOf(e), err
}

func (q *ActivityQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Activity, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return activityOf(e), err
}

func (q *ActivityQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Activity, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return activityOf(e), err
}

func (q *ActivityQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (ActivityCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return ActivityCollectionOf(rows), err
}

func (q *ActivityQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Activity, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return activityOf(e), err
}

func (q *ActivityQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Activity, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return activityOf(e), err
}

func (q *ActivityQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Activity, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return activityOf(e), err
}

func (q *ActivityQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Activity, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return activityOf(e), err
}

func (q *ActivityQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (ActivityCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return ActivityCollectionOf(rows), meta, err
}

func (q *ActivityQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (ActivityCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return ActivityCollectionOf(rows), meta, err
}

func (q *ActivityQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (ActivityCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return ActivityCollectionOf(rows), meta, err
}

func (q *ActivityQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(ActivityCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(ActivityCollectionOf(rows), page)
	})
}

func (q *ActivityQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Activity, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(activityOf(e), index)
	})
}

func (q *ActivityQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Activity, error] {
	return func(yield func(*Activity, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(activityOf(e), err) {
				return
			}
		}
	}
}

func (q *ActivityQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *ActivityQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *ActivityQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *ActivityQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *ActivityQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *ActivityQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *ActivityQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *ActivityQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *ActivityQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *ActivityQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *ActivityQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *ActivityQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *ActivityQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *ActivityQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *ActivityQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *ActivityQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *ActivityQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *ActivityQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *ActivityQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c ActivityCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c ActivityCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c ActivityCollection) Find(key any) *Activity { return activityOf(c.Rows().Find(key)) }

func (c ActivityCollection) FindOrFail(key any) (*Activity, error) {
	e, err := c.Rows().FindOrFail(key)
	return activityOf(e), err
}

func (c ActivityCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c ActivityCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c ActivityCollection) Only(keys ...any) ActivityCollection {
	return ActivityCollectionOf(c.Rows().Only(keys...))
}

func (c ActivityCollection) Except(keys ...any) ActivityCollection {
	return ActivityCollectionOf(c.Rows().Except(keys...))
}

func (c ActivityCollection) Unique() ActivityCollection {
	return ActivityCollectionOf(c.Rows().Unique())
}

func (c ActivityCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c ActivityCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c ActivityCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c ActivityCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (ActivityCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return ActivityCollectionOf(rows), err
}

func (c ActivityCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Activity; it shadows the untyped one the
// embedded model promotes.
func (row *Activity) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Activity, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return activityOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Activity) Replicate(except ...string) (*Activity, error) {
	e, err := row.Model.Replicate(except...)
	return activityOf(e), err
}
